### PR TITLE
Added API to append sources to the asset at runtime.

### PR DESCRIPTION
**Pull request by exileDev**
Sometimes we need to add files to the bundle at runtime (e.g., by a condition in Razor markup). At now, if we're trying to add a file, the bundle won't be updated until the clear cache.

### CODE REVIEW

**Comment by exileDev** [comment]
Anyway, please update the package version. We're doing a release this month. =)

**Comment by AndreiMaz** [comment]
@madskristensen It would be great if you can be merge this pul lrequest

**Comment by madskristensen** [comment]
Thank you!

**Comment by objectstudio** [comment]
This PR causes the Sass plugin to break (LigerShark.WebOptimizer.Sass/3.0.73-beta).

The plugin appears to depend on the IAsset.SourceFiles being an enumerable as it was in previous versions (3.0.335 and below). Throws a Missing Method exception at this line in v3.0.344):

Compiler - Line 117:
foreach (var route in _asset.SourceFiles.Where(f => f.EndsWith(".scss")))

I had to roll back to 3.0.335 to use the Sass plugin.

**Pull request merged**
