### PR TITLE
change to concurrent dictionary

### PR DESCRIPTION
**Pull request by jasonliao-cb**

### CODE REVIEW

**Comment by jasonliao-cb** [comment]
this is for issue https://github.com/ligershark/WebOptimizer/issues/228

**Comment by daneSchilling** [comment]
I was able to replicate similar issues by running parallel tasks racing to make the first request to `GenerateCacheKey` on a single instance of `Asset`. With the change above, I am able to run parallel tasks without issue.

With the tests I created, I was getting `NullReferenceException` on the code: `asset.Items[PhysicalFilesKey] = files;`

**Comment by daneSchilling** [comment]
@jasonliao-cb I would love for this to get merged. Maybe add the author as the reviewer? They may ask you to remove the unrelated gitignore changes. Thanks again for opening the PR!

**Comment by madskristensen** [comment]
Thanks

**Comment by daneSchilling** [comment]
Thank you!

**Comment by exileDev** [comment]
@madskristensen Can you publish the latest version?

**Comment by madskristensen** [comment]
Yes, releasing now...

**Pull request merged**
